blog/urls.py
from django.urls import path, include
from .views import blog_view, create_post,users_blog
from .views import PostDeleteView


app_name="Blogs"

urlpatterns=[
    path('', blog_view, name='blog'),
    path('post/',create_post,name='create_post'),
    path('userblogs/',users_blog,name='users_blogs'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
 ]

main/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='home' ),
    path('survey',views.survey,name="survey"),
]

ngo/urls.py
from django.urls import path, include
from . import views


urlpatterns = [

    path('register/ngo-survey',views.ngo_survey,name = "ngo_survey"),
    path('register/indv-survey',views.indv_survey,name = "indv_survey"),
    path('register/indus-survey',views.indus_survey,name = "indus_survey"),
]

sustain/urls.py
from django.contrib import admin
from django.urls import path, include
from register.views import register,category
from login.views import log_in
from django.contrib.auth.views import LogoutView
from django.conf import settings
from blog.views import blog_view
from django.conf.urls.static import static
from ngo import urls
from leaderboard import urls
from quiz.views import quiz
from pledge.views import send_pledge
from orgs_and_ngos.views import orgs_view,ngos_view
from carbon_footprint.views import c_footprint
from articles.views import article
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls') ),
    path('blog/',include('blog.urls') ),
    path('register/', register, name='register' ),
    path('register/category', category, name='category' ), #added for category selection
    path('login/', log_in , name='login'),
    path('', include('social_django.urls', namespace='social')),
    path('logout/',LogoutView.as_view(template_name=settings.LOGOUT_REDIRECT_URL),name='logout'),
    path('',include('ngo.urls')),#for viewing and registring NGO,Indu,Indiv survey and ping
    path('',include('leaderboard.urls')),#for viewing and registring NGO,Indu,Indiv survey and ping
    path('quiz/',quiz, name='quiz' ),
    path('pledge/',send_pledge, name='pledge' ),##arithmeticpal
    
    path('orgs/', orgs_view, name='orgs' ),
    path('ngos/', ngos_view, name='ngos' ),
    path('carbon_footprint/', c_footprint, name='carbon_footprint' ),
    path('articles/',article, name='articles' ),




]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django.forms import ModelForm
from .models import Blog

class post_form(ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content' ,'images']

class BlogUpdateForm(ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content' ,'images']

ngo/forms.py
from django import forms
from .models import Ngo

class NGO_form(forms.ModelForm):
    class Meta:
        model= Ngo
        fields=['name' , 'objective' , 'description' , 'scope' , 'reg_no' , 'website' , 'email' , 'contribution' , 'image']

register/forms.py
from django import forms

articles/views.py
from django.shortcuts import render
from .models import Article

# Create your views here.
def article(request):

    article  = Article.objects.all()

    return render(request , 'article.html',{'article':article})

blog/views.py
from django.shortcuts import render,redirect
from .models import Blog
from django.shortcuts import get_object_or_404 
import json
from django.http import HttpResponse
from .forms import post_form
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView,UpdateView,DeleteView


def blog_view(request):
   if request.method =="POST":
       if request.POST.get("operation") == "like_submit" and request.is_ajax():
         content_id=request.POST.get("content_id",None)
         content=get_object_or_404(Blog,pk=content_id)
         if content.likes.filter(id=request.user.id): #already liked the content
            content.likes.remove(request.user) #remove user from likes 
            liked=False
         else:
             content.likes.add(request.user) 
             liked=True
         ctx={"likes_count":content.total_likes,"liked":liked,"content_id":content_id}
         return HttpResponse(json.dumps(ctx), content_type='application/json')

   contents=Blog.objects.all()
   already_liked=[]
   id=request.user.id
   for content in contents:
       if(content.likes.filter(id=id).exists()):
        already_liked.append(content.id)
   context={"contents":contents,"already_liked":already_liked}
   return render(request,"blog.html",context)
   
def create_post(request):
    if request.method=="POST":
        form=post_form(request.POST , request.FILES)
        form.instance.author=request.user
        if form.is_valid():
            form.save()
            return redirect('Blogs:blog')
    else:
        form=post_form()
    return render(request,'add_blog.html',{'form':form})   

class PostDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Blog
    success_url = '/blog/userblogs/'
    template_name = 'blog_delete.html'

    def test_func(self):
        post=self.get_object()
        if self.request.user==post.author:
            return True
        return False

def users_blog(request):
    contents=Blog.objects.all().filter(author=request.user)
    return render(request, 'user_blogs.html',{'contents':contents})

carbon_footprint/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from .models import Carbon_footprint
import datetime




# Create your views here.
def c_footprint(request):
    today = datetime.datetime.now().date()
    x=Carbon_footprint.objects.filter(user=request.user)
    if x :
        x=x[0].date
        if x==today:
            return render(request,'404.html')
    if request.method=='POST':
        x=Carbon_footprint.objects.create(
            user=request.user,
            electric= request.POST["electric"], 
            gas=request.POST["gas"],
            oil=request.POST["oil"],
            car=request.POST["car"],
            flights=request.POST["flights"],
            day  =request.POST["dayOptionsRadios"],
            meal=request.POST["mealOptionsRadios"],
        )
        x.save()

        return redirect('carbon_daily')
    return render(request , 'carbon_footprint.html')

leaderboard/views.py
from django.shortcuts import render ,redirect
from ngo.models import Industry,Individual
from register.models import Category
from django.contrib.auth.models import User
from .models import Indus_lb,Indv_lb,Carbon_fp
from carbon_footprint.models import Carbon_footprint
from django.utils import timezone
import datetime


# Create your views here.



def result_main(request):
    user = request.user
    cat = Category.objects.filter(user=request.user)
    category =  cat[0].category

    # if category == 'ngo':
    if category == 'industry':
        score = 0
        data = Industry.objects.filter(user=user)
        for i in data:
            if i.pollution == 'yes':
                score = score + 10
            if i.sustainibility =='yes':
                score = score +5
            if i.plant =='yes':
                score = score +10
            if i.untreated_sewage =='no':
                score = score + 10
            if i.untreated_sewage =='yes':
                score = score -15
            if i.emp_month =='yes':
                score = score +15
            if i.env_audit =='yes':
                score = score + 15
            if i.garbage =='to some extent':
                score = score + 5
            if i.garbage =='a lot':
                score = score + 15
            if i.employment =='a lot':
                    score = score + 10
            if i.employment =='to some extent':
                score = score + 5
            if i.health =='a lot':
                score = score + 10
            if i.health =='to some extent':
                score = score + 5
            if i.recycle =='a lot':
                score = score + 15
            if i.recycle =='to some extent':
                score = score + 5
            if i.responsibility =='a lot':
                score = score + 15
            if i.responsibility =='to some extent':
                score = score + 5
            if i.energy == 'non_conventional':
                score = score + 15
            if i.energy == 'mix':
                score = score + 5
            if i.water_source == 'River/lake':
                score = score + 10
            if i.water_source == 'Ground water' or i.water_source == 'Municipal water':
                score = score + 5
            if i.water_source == 'Rain water':
                score = score + 20
            if i.effluent_q == '>50%':
                score = score - 20
            if i.effluent_q == '30%':
                score = score - 15
            if i.effluent_q == '20%':
                score = score - 10
            if i.effluent_q == '1%':
                score = score + 5
            final = (score/180)*100
            try:
                x = Indus_lb.objects.create(
                    user=request.user,
                    score = final,
                )
                x.save()
                score_in = Indus_lb.objects.filter(user=user)
                return render(request,'result-main.html',{'score_in':score_in})
            except:
                score_in = Indus_lb.objects.filter(user=user)
                return render(request,'result-main.html',{'score_in':score_in})
                
    if category == 'individual':
        score = 0
        data = Individual.objects.filter(user=user)
        for i in data:
        

            if i.garbage =='to some extent':
                score = score + 5
            if i.garbage =='a lot':
                score = score + 15
                
            if i.waste_water == 'a lot':
                score = score -10
            if i.waste_water == 'to some extent':
                score = score -5
            if i.waste_water == 'not at all':
                score = score +10

            if i.biodegradable == 'a lot':
                score = score +15
            if i.biodegradable == 'to some extent':
                score = score +10
            if i.biodegradable == 'not at all':
                score = score +0


            if i.recycle == 'a lot':
                score = score +15
            if i.recycle == 'to some extent':
                score = score +10
            if i.recycle == 'not at all':
                score = score +0


            if i.govt == 'a lot':
                score = score +15
            if i.govt == 'to some extent':
                score = score +10
            if i.govt == 'not at all':
                score = score +0

            if i.disposal == 'a lot':
                score = score -10
            if i.disposal == 'to some extent':
                score = score -5
            if i.disposal == 'not at all':
                score = score +10

            if i.energy == 'a lot':
                score = score +15
            if i.energy == 'to some extent':
                score = score +10
            if i.energy == 'not at all':
                score = score -5

            if i.bulb == 'yes':
                score = score +10
            if i.bulb == 'no':
                score = score -5

            if i.cfc == 'yes':
                score = score -10
            if i.cfc == 'no':
                score = score +10
            
            if i.news == 'yes':
                score = score +10
            if i.news == 'no':
                score = score +0

            if i.plant == 'yes':
                score = score +25
            if i.plant == 'no':
                score = score +0

            if i.travel == 'public':
                score = score +15
            if i.travel == 'private':
                score = score +0
            if i.travel == 'carpool':
                score = score +10
            
            if i.plant == 'veg':
                score = score +25
            if i.plant == 'non_veg':
                score = score +0
            if i.plant == 'mostly veg':
                score = score +5
               
            final = (score/180)*100
            try:
                x = Indv_lb.objects.create(
                    user=request.user,
                    score = final,
                )
                x.save()
                score_in = Indv_lb.objects.filter(user=user)
                return render(request,'result-main.html',{'score_in':score_in})
            except:
                score_in = Indv_lb.objects.filter(user=user)
                return render(request,'result-main.html',{'score_in':score_in})
        
    return render(request,'result-main.html')

def carbon_daily(request):
    today = datetime.datetime.now().date()
    user = request.user
    x=Carbon_fp.objects.filter(user=request.user)
    if x :
        x=x[0].date
        if x==today:
            score_in = Carbon_fp.objects.filter(date = today).filter(user=user)
            return render(request,'result-main.html',{'score_in':score_in})
    data = Carbon_footprint.objects.filter(date=today).filter(user=user)
    carb_fp=0
    print(data[0].electric)
    for i in data:
        carb_fp = carb_fp + float(i.electric)*0.75
        carb_fp = carb_fp + (float(i.gas)*0.3*1665)/1000
        carb_fp = carb_fp + (float(i.oil)*2500)/1000
        carb_fp = carb_fp + (float(i.car)*123)/1000
        carb_fp = carb_fp + (float(i.flights)*90)
        if i.meal =='yes':
            carb_fp = carb_fp + 0.4
        else:
            carb_fp = carb_fp +0.7
            
        x = Carbon_fp.objects.create(
            user= user,
            carbon = carb_fp
        )
        x.save()

    score_in = Carbon_fp.objects.filter(date = today).filter(user=user)
    return render(request,'result-main.html',{'score_in':score_in})

    # return render(request ,'result-main.html')



def lb(request):


    indus  = Indus_lb.objects.all()
    indv   = Indv_lb.objects.all()

    today = datetime.datetime.now().date()
    x=Carbon_fp.objects.filter(date=today)




    context = {
        'indus':indus,
        "indv" :indv,
        'carbon_fp':x,
    }



    return render(request,'leaderboard.html',context)

login/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User,auth
from django.contrib import messages
from django.contrib.auth import authenticate, login
# Create your views here.
def log_in(request):
    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'Login Successful')
            
            return redirect('home')
            
        else:
            messages.info(request, 'Invalid Credentials')

            return redirect('login')

    return render(request,'login.html' )

ngo/views.py
from django.shortcuts import render, redirect
from .models import Ngo, Individual, Industry
from register.models import Category
# Create your views here.
from .forms import NGO_form


def ngo_survey(request):

    if request.method == "POST":
        form  = NGO_form (request.POST, request.FILES)
        form.instance.user=request.user
        if 1:
            print(form)
            form.save()
            return  redirect('home')
    
    else:
        form = NGO_form()
        

    return render(request, 'ngo-survey.html' , {'form' : form})


def indv_survey(request):

    if request.method == "POST":
        x = Individual.objects.create(
            user=request.user,
            tank_cap=request.POST["tank_cap"],
            member=request.POST["member"],
            garbage=request.POST["garbage"],
            waste_water=request.POST["waste_water"],
            biodegradable=request.POST["biodegradable"],
            recycle=request.POST["recycle"],
            govt=request.POST["govt"],
            disposal=request.POST["disposal"],
            energy=request.POST["energy"],
            bulb=request.POST["bulb"],
            cfc=request.POST["cfc"],
            news=request.POST["news"],
            plant=request.POST["plant"],
            travel=request.POST["travel"],
            diet=request.POST["diet"],
        )
        x.save()
        return redirect('result_main')

    return render(request, "individual-survey.html")


def indus_survey(request):
    if request.method == "POST":
        x = Industry.objects.create(
            user=request.user,
            name=request.POST["name"],
            turnover=request.POST["turnover"],
            pollution=request.POST["pollution"],
            sustainibility=request.POST["sustainibility"],
            csr_def=request.POST["csr_def"],
            plant=request.POST["plant"],
            untreated_sewage=request.POST["untreated_sewage"],
            emp_month=request.POST["emp_month"],
            env_audit=request.POST["env_audit"],
            garbage=request.POST["garbage"],
            employment=request.POST["employment"],
            health=request.POST["health"],
            recycle=request.POST["recycle"],
            responsibility=request.POST["responsibility"],
            energy=request.POST["energy"],
            water_source=request.POST["water_source"],
            effluent=request.POST["effluent"],
            effluent_q=request.POST["effluent_q"],
            nature_waste=request.POST["nature_waste"],
        )
        x.save()
        return redirect('result_main')
    return render(request, 'industry-survey.html')

main/templates/add_blog.html
{% extends "base.html"%}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section" style="margin-left: 30%;">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                   Add your good deed!<br>
                    let it inspire others
                </legend>
                {{form|crispy}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-success ml-5 px-5" type="submit">Post!!!</button>
            </div>
        

        </form>
    </div>
{% endblock content%}

main/templates/article.html
{% extends "base.html"%}
{% block content %}



<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">Articles</h1>

    {% for i in article %}
    <div class="card shadow mb-4">
        <!-- Card Header - Accordion -->
        <div class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="false"
            aria-controls="collapseCardExample">
            <h6 class="m-0 font-weight-bold text-primary">{{i.title}}</h6>
        </div>


        <!-- Card Content - Collapse -->
        <div class="collapse show" id="collapseCardExample">
            <div class="card-body">
                
                <img class="img-responsive" src=" {{i.images.url}} " alt="{{ i.title }}"
                    style="width: 50%; height: 300px; float: left; margin-right: 30px;">
                
                <div>
                {{i.content}}
                </div>
                
                
            </div>
        </div>
    </div>


    {% endfor %}

</div>

{% endblock content%}

main/templates/carbon.html
<div class="chart" id="regions_div"> </div>

<script
  type="text/javascript"
  src="https://www.gstatic.com/charts/loader.js"
></script>
<script type="text/javascript">
  google.charts.load("current", { packages: ["geochart", "corechart"]});
  google.charts.setOnLoadCallback(drawRegionsMap);
  google.charts.setOnLoadCallback(drawChart);

  function drawRegionsMap() {
    var data = google.visualization.arrayToDataTable([
      ["Country", "carbon emission"],
      ["Afghanistan", 0.3],
      ["Albania", 1.6],
      ["Algeria", 3.9],
      ["American Samoa", 0.0],
      ["Andorra", 6.0],
      ["Angola", 1.0],
      ["Antigua and Barbuda", 6.2],
      ["Argentina", 4.7],
      ["Armenia", 2.0],
      ["Aruba", 9.3],
      ["Australia", 16.8],
      ["Austria", 8.2],
      ["Azerbaijan", 3.5],
      ["Bahamas", 7.7],
      ["Bahrain", 21.8],
      ["Bangladesh", 0.6],
      ["Barbados", 11.6],
      ["Belarus", 6.8],
      ["Belgium", 9.2],
      ["Belize", 1.2],
      ["Benin", 0.7],
      ["Bermuda", 7.2],
      ["Bhutan", 1.9],
      ["Bolivia", 2.0],
      ["Bosnia and Herzegovina", 7.8],
      ["Botswana", 3.2],
      ["Brazil", 2.4],
      ["British Virgin Islands", 4.8],
      ["Brunei", 16.0],
      ["Bulgaria", 6.3],
      ["Burkina Faso", 0.2],
      ["Burundi", 0.0],
      ["Cape Verde", 1.9],
      ["Cambodia", 0.7],
      ["Cameroon", 0.6],
      ["Canada", 16.1],
      ["Cayman Islands", 8.1],
      ["Central African Republic", 0.1],
      ["Chad", 0.0],
      ["Chile", 5.0],
      ["China", 8.0],
      ["Colombia", 1.8],
      ["Comoros", 0.3],
      ["Democratic Republic of the Congo", 0.0],
      ["Republic of the Congo", 1.3],
      ["Cook Islands", 2.4],
      ["Costa Rica", 1.8],
      ["Ivory Coast", 0.6],
      ["Croatia", 4.7],
      ["Cuba", 2.4],
      ["Curaçao", 52.1],
      ["Cyprus", 6.3],
      ["Czech Republic", 10.4],
      ["Denmark", 5.8],
      ["Djibouti", 1.1],
      ["Dominica", 1.7],
      ["Dominican Republic", 2.3],
      ["Ecuador", 2.6],
      ["Egypt", 2.5],
      ["El Salvador", 1.2],
      ["Equatorial Guinea", 2.5],
      ["Eritrea", 0.2],
      ["Estonia", 18.6],
      ["Eswatini", 0.9],
      ["Ethiopia", 0.2],
      ["Falkland Islands", 13.6],
      ["Faroe Islands", 0.0],
      ["Fiji", 1.4],
      ["Finland", 8.8],
      ["France", 5.0],
      ["French Guiana", 2.6],
      ["French Polynesia", 2.0],
      ["Gabon", 3.2],
      ["Gambia", 0.3],
      ["Georgia", 2.8],
      ["Germany", 9.1],
      ["Ghana", 0.7],
      ["Gibraltar", 19.6],
      ["Greece", 6.5],
      ["Greenland", 9.4],
      ["Grenada", 2.7],
      ["Guadeloupe", 5.2],
      ["Guam", 0.1],
      ["Guatemala", 1.2],
      ["Guinea", 0.2],
      ["Guinea-Bissau", 0.2],
      ["Guyana", 2.5],
      ["Haiti", 0.3],
      ["Honduras", 1.1],
      ["Hong Kong", 6.1],
      ["Hungary", 5.4],
      ["Iceland", 12.1],
      ["India", 1.9],
      ["Indonesia", 2.1],
      ["Iran", 8.9],
      ["Iraq", 4.8],
      ["Ireland", 7.7],
      ["Isle of Man", 0.0],
      ["Israel", 7.9],


    ],);

    var options = {
      colorAxis: {
        colors: [
          "#333333",
          "#112222",
          "#696969",
          "#808080",
          "#020403",
          "#4a4b46",
          "#343434",
          "#0d0c0a",
          "#3b3c36",
          "#777672",
        ],
      },
      legend: "none",
    };

    var chart = new google.visualization.GeoChart(
      document.getElementById("regions_div")
    );
    chart.draw(data, options);
  }
</script>
<script>
  $(document).ready(function () {
    $(window).resize(function () {
      drawRegionsMap();
    });
  });
</script>
<style>
  .chart {
    width: 100%;
    height: 400px;
  }
</style>

main/templates/login.html
{% extends "base.html"%}
{% block content %}

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                  </div>
                  <form class="user" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                      <input type="email" name="username" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                    </div>
                    <div class="form-group">
                      <input type="password" name="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Password">
                    </div>
                    
                    <button type="submit" class="btn btn-primary btn-user btn-block">
                      Login
                    </button>
                    <hr>
                    <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-google btn-user btn-block">
                      <i class="fab fa-google fa-fw"></i> Login with Google
                    </a>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="forgot-password.html">Forgot Password?</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="{% url 'register' %}">Create an Account!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  {% endblock content%}

main/templates/ngo-survey.html
{% extends "base.html"%}
{% block content %}

<body class="bg-gradient-primary" >

  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-12">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Let us know your NGO better!</h1>
              </div>
              <form class="user" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% load widget_tweaks %}
              
                <div class="form-group">
                    <label for="exampleFormControlSelect1">
                      NGO\Organizational name</label>
                      {{ form.name  }}
                  </div>

                  <div class="form-group">
                    <label for="exampleFormControlSelect1">
                      NGO\Organizational Motto</label>
                      {{ form.objective }}
                  </div>

                  <div class="form-group">
                    <label for="exampleFormControlSelect1">
                      NGO\Organizational description</label>
                      <br>
                      {{ form.description }}
                  </div>


                <div class="form-group">
                  <label for="exampleFormControlSelect1">scope </label>
                  {{ form.scope }}
                </div>
                <div class="form-group">
                  <label for="exampleFormControlSelect1">Registration Number
                     </label>
                     {{ form.reg_no }}
                </div>

                <div class="form-group">
                    <label for="exampleFormControlSelect1">Website
                      . </label>
                      {{ form.website }}
                  </div>
                  <div class="form-group">
                    <label for="exampleFormControlSelect1">email
                      . </label>
                      {{ form.email }}
                  </div>
                  <div class="form-group">
                    <label for="exampleFormControlSelect1">Image
                      . </label>
                      {{ form.image }}
                  </div>
                  <div class="form-group">
                    <label for="exampleFormControlSelect1">Past Contributions
                      . </label>
                      <br>
                      {{ form.contribution }}
                  </div>

                  <button type="submit" class="btn btn-primary btn-user btn-block">
                    Submit!
                  </button>


              </form>
              <hr>
              
          
          
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>

  {% endblock content%}

main/templates/result-main.html
{% extends "base.html"%}
{% block content %}

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Here are your results </h1>
                  </div>
                 
                  <hr>
                 {% for i in score_in %}
               
               <div> {{ i.user.first_name }}  <br>
                
                 You've got {{  i.carbon }}{{i.score}}</div> 


                 {% endfor %}
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  {% endblock content%}

main/templates/user_blogs.html
{% extends "base.html"%}
{% block content %}

   

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-4 text-gray-800">Nature Book</h1>

          {% for content in contents %}
          <div class="card shadow mb-4">
            <!-- Card Header - Accordion -->
            <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="collapseCardExample">
              <h6 class="m-0 font-weight-bold text-primary">{{content.title}}</h6>
              <small class="text-muted">{{ content.time| date:"F d, Y" }}</small>
              <div style="float: right;" ><strong> {{content.author.first_name}}</strong></div>
            </a>
            <div class="card-body">
              {{content.description}}
            </div>
            <!-- Card Content - Collapse -->
            <div class="collapse show" id="collapseCardExample">
              <div class="card-body">
               
                <img class="img-responsive" src=" {{content.images.url}} " alt="{{ content.title }}" style="width: 50%; height: 300px; float: left; margin-right: 30px;">
                {{content.content | safe}}
        
              </div>
            </div>
          </div>
          <div>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'Blogs:post-delete' content.id %}">Delete</a>
            </div>
          {% endfor %}

        </div>
        <!-- /.container-fluid -->

  

  {% endblock content%}